version: '3.1'

services:
  mariadb:
    image: mariadb:latest
    container_name: rpg-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rpg
      MYSQL_USER: rpg
      MYSQL_PASSWORD: rpgp
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: